version: '3.8'

services:
  node-app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
    command: npm start

  nginx:
    image: nginx:alpine
    ports:
      - "8087:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app